version: "3.8"

services:

  # 1. Python_Images
  images:
    image: brianduran/python_images:v1
    ports:
      - "5000:5000"
    environment:
      - UPLOAD_FOLDER=/app/uploads
    volumes:
      - ./python_images/uploads:/app/uploads

  # 2. Java_Sighting
  sightings:
    image: brianduran/java_sighting:v1
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/databaseName
      - SPRING_DATASOURCE_USERNAME=the_username
      - SPRING_DATASOURCE_PASSWORD=the_password
    depends_on:
      - db

  # 3. Postgres
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: databaseName
      POSTGRES_USER: the_username
      POSTGRES_PASSWORD: the_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # 4. Node_Cars
  cars:
    image: brianduran/node_cars:v1
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  # 5. Mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 6. Nginx
  nginx:
    image: brianduran/nginx:v2
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - images
      - sightings
      - cars

# Se persistirán los datos de Posgres y Mongo
volumes:
  db_data:
  mongo_data:
