FROM nginx:latest

# Copia el archivo default.conf al directorio de configuración de Nginx
COPY default.conf /etc/nginx/conf.d/default.conf

# Copia la carpeta html al directorio de recursos estáticos de Nginx
COPY ./html /usr/share/nginx/html
