# Imagen de maven para compilar la el proyecto
FROM maven:3.9.7-eclipse-temurin-21-alpine AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

# Descargar las dependencias sin compilar la aplicación
# Generar el .jar
RUN mvn clean package

# Etapa de ejecución
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

# Copiar el archivo JAR desde la imagen anterior (jdk21)
COPY --from=build /app/target/java_sighting-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto que usará la aplicación
EXPOSE 8080

# Variables de entorno para configurar la base de datos
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

# Comando para ejecutar la aplicación
CMD ["java", "-jar", "app.jar"]
